### PR TITLE
error correction

### LINKED ISSUE #1: Distribute your code into modules
Hallo @clinton-33 

kindly separate concerns in your code: after our ADT discussions we should Expect that you are able to separate each ADT into its module.

### LINKED ISSUE #2: Make BaseTransaction class concrete
Hi @clinton-33 ,

Your implementation of the BaseTransactions class is not the required implementation
We need to change the BaseTransactions class to a concrete class with a default app() method.

Then override this I, implementation in both the DepositTransaction and Withdrawaltransaction such that the behavior of this method depends on which of the three classes has been instantiated.

**Steps to Accomplish this**

1. Create a branch of your repo and perform these modifications then commit to the branch.
2. Create a pull request to merge your newly pushed branch to the main branch and add me as a reviewer.
3. Add this issue to the pull request so that when the pull request is merged after my review, this issue automatically closes.
4.. Once I review, the pull request will be merged into your main repo and that will be that.

### LINKED ISSUE #3: Incomplete Specification
Hi @clinton-33,

Your specifications for all the ADTs aren't done, so please make sure you complete these.
Take a look at how the specification is done in our lecture codes here: --> https://github.com/mulangonando/Advanced-Programming/blob/main/src/Lecture2_adt_specification/Transaction4.java --> These were not full specifications either but seek to make full specification.

**Steps to Accomplish this**

1. Create a branch of your repo and perform these modifications then commit to the branch.
    - Ensure your specification includes descriptions for the requires and produces interfaces, the pre-conditions, and post-conditions
2. Create a pull request to merge your newly pushed branch to the main branch and add me as a reviewer.
3. Add this issue to the pull request so that when the pull request is merged after my review, this issue automatically closes.
4.. Once I review, the pull request will be merged into your main repo and that will be that.

### LINKED ISSUE #4: Incomplete Exception Handling
Hi @clinton-33 ,

Exception handling, beyond defining the exception class please use it in a function (throw or try catch block)

**Steps to Accomplish this**

1. Create a branch of your repo and perform these modifications then commit to the branch.
2. Create a pull request to merge your newly pushed branch to the main branch and add me as a reviewer.
3. Add this issue to the pull request so that when the pull request is merged after my review, this issue automatically closes.
4. once I review, the pull request will be merged into your main repo and that will be that.

### PR DESCRIPTION
**Pull request by clinton-33**

### CODE REVIEW

File: BankAccount.java [hunk 1]
```diff
@@ -0,0 +1,27 @@
+package transactionsystem;
+/**
```
Comment (mulangonando) [inline BankAccount.java:2]: Your specification is still not complete. Please perform  proper specification. You can learn from Bridgit Wanjiru. Or Joseph

File: BaseTransaction.java [hunk 2]
```diff
@@ -0,0 +1,38 @@
+package transactionsystem;
+
+import java.util.Calendar;
+/**
+ * Abstract base class representing a financial transaction.
```
Comment (mulangonando) [inline BaseTransaction.java:7]: For the Assignment the BaseTransaction needs to concrete

**Review by mulangonando — CHANGES_REQUESTED** [review]
Please complete the task as per the assignment

**Review by mulangonando — APPROVED** [review]
I will merge this but there's some things not done right still. Perhaps after your exams you can review them for your own benefit.
